version: '3'

services:
    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "777:80"
        volumes:
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./images:/images
        restart: always